query = sprintf(['SELECT id FROM params WHERE', ' ', ...
				'rwrdThreshold = %d AND width = %d AND maxRwrd = %d', ...
				' ', 'AND maxPen = %d AND singleOccScore = %d AND', ...
				' ','missingScore = %d AND lockout = %d AND type = %s;'], ...
				2, 0.35, 2, 1, 3, 3.3, 90, '"simpleSMD"');
			curs = exec(obj.conn, query);
			curs = fetch(curs);